// Generated by CoffeeScript 1.6.3
(function() {
  var EscomplexDecorator, ReportDecorator, escomplex, walker,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  ReportDecorator = require('../report_decorator').ReportDecorator;

  escomplex = require('escomplex');

  walker = require('escomplex-ast-moz');

  EscomplexDecorator = (function(_super) {
    __extends(EscomplexDecorator, _super);

    function EscomplexDecorator() {
      EscomplexDecorator.__super__.constructor.apply(this, arguments);
      this.process = function(sourceTree) {
        var file, files, name, report;
        files = sourceTree.getFiles();
        for (name in files) {
          if (!__hasProp.call(files, name)) continue;
          file = files[name];
          report = escomplex.analyse(file.syntax, walker, {});
          sourceTree.addReport(name, report);
        }
        return this.component.process(sourceTree);
      };
    }

    return EscomplexDecorator;

  })(ReportDecorator);

  exports.EscomplexDecorator = EscomplexDecorator;

}).call(this);
