// Generated by CoffeeScript 1.6.3
(function() {
  var ReportComponent,
    __hasProp = {}.hasOwnProperty;

  ReportComponent = (function() {
    function ReportComponent() {}

    ReportComponent.prototype.process = function() {};

    ReportComponent.prototype.traverse = function(object, visitor, prev) {
      var child, key, _results;
      if (visitor.call(null, object, prev) === false) {
        return;
      }
      _results = [];
      for (key in object) {
        if (!__hasProp.call(object, key)) continue;
        child = object[key];
        if (typeof child === "object" && (child != null)) {
          _results.push(this.traverse(child, visitor, object));
        } else {
          _results.push(void 0);
        }
      }
      return _results;
    };

    ReportComponent.prototype.getParseErrorReport = function(err, filename, decorator) {
      var output;
      output = "Error parsing " + filename + "\n  at parse (" + decorator + ")\n\n  " + err;
      return output;
    };

    return ReportComponent;

  })();

  exports.ReportComponent = ReportComponent;

}).call(this);
