// Generated by CoffeeScript 1.6.3
(function() {
  var ReportComponent, ReportDecorator,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  ReportComponent = require('./report_component').ReportComponent;

  ReportDecorator = (function(_super) {
    __extends(ReportDecorator, _super);

    function ReportDecorator(component) {
      this.component = component;
    }

    ReportDecorator.prototype.process = function() {
      return this.component.process();
    };

    return ReportDecorator;

  })(ReportComponent);

  exports.ReportDecorator = ReportDecorator;

}).call(this);
