// Generated by CoffeeScript 1.6.3
(function() {
  var ReportComponent, SimpleReportComponent, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  ReportComponent = require('./report_component').ReportComponent;

  SimpleReportComponent = (function(_super) {
    __extends(SimpleReportComponent, _super);

    function SimpleReportComponent() {
      _ref = SimpleReportComponent.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    SimpleReportComponent.prototype.process = function() {};

    return SimpleReportComponent;

  })(ReportComponent);

  exports.SimpleReportComponent = SimpleReportComponent;

}).call(this);
